### ISSUE TITLE
disable sass-lint-result.xml creation when there are no sass issues.

### ISSUE THREAD

**Issue by jotka** [Nykredit/gript#15]
When there are no Sass issues, the empty sass-lint-result.xml file is being created. This makes Jenkins build failing - trying to parse an empty file. The file should not be generated in such case or it should be valid _empty_ XML file. As requested by @hindsholm

**Comment by hindsholm** [comment]
I assume you mean `scss-lint-result.xml`, not `sass-lint-result.xml` :)
The [gulp-scss-lint documentation](https://www.npmjs.com/package/gulp-scss-lint) says that you just need to add a property to the configuration in order to generate Checkstyle-formatted output:
```javascript
gulp.src(['**/*.scss'])
  .pipe(scsslint({
    'reporterOutputFormat': 'Checkstyle',
  }))
```
This might also resolve this issue.

**Comment by jotka** [comment]
yes, of course scss-lint-result.xml :)

**Comment by jotka** [comment]
adding 'reporterOutputFormat': 'Checkstyle' will produce an empty XML:

```xml
<?xml version="1.0" encoding="utf-8"?>
<checkstyle version="1.5.6"></checkstyle>
```

but the mandatory gem needs to be installed:

Error: You need to have the scss_lint_reporter_checkstyle gem installed

updating readme with this and closing the issue on master. npm release soon.
