### ISSUE TITLE
target/tmp/js folder (contaning modernizr.js) seems to be include in code coverage report

### ISSUE THREAD

**Issue by jensborch** [Nykredit/gript#70]
On Jenkins the target/tmp/js folder (contaning modernizr.js) seems to be include in code coverage report. This is probably an error.

**Comment by Mortenagoda** [comment]
I Just experienced this too. I agree. Only project sources should be included in the coverage report.

**Comment by jotka** [comment]
ok, but target/tmp/js contains the javascripts coming from the typescript sources, so It needs to be included in the coverage. However, I can exclude the modernizr.js.

**Comment by hindsholm** [comment]
We have the same problem, but we also get all of bower_components included in our code coverage, see e.g. http://jenkins/job/38/job/39/job/mitnykredit%20feature/399/cobertura/
The problem is, that `karma.preprocessors` has a default value of `'!(patch)/**/!(*_test).js': ['coverage']` which cannot be overridden, it can only be appended to.

**Comment by hindsholm** [comment]
Fix suggested in #83

**Comment by jotka** [comment]
Merged the fix thanks - release today or tomorrow.

**Comment by jotka** [comment]
published as 0.0.53
