### ISSUE TITLE
Current app-cache configuration dosn't work

### ISSUE THREAD

**Issue by jensborch** [Nykredit/gript#94]
Everything that links to the app-cache manifest file is also cached. In Gript index.html links to the mainfest file, the index.html file is thus cached, but the index.html file is not static. Gript will e.g. inject new dependencies into index.hml. These changes will thus not be picked up by the browser leading to errors.

**Comment by langecode** [comment]
But the app.cache manifest is updated with every build (the timestamp is changed). So following a new release the browser will detect a new app.cache manifest and re-cache all the cached resources. So it should not be a problem that cached resources might change as long as this is signalled by changing the app.cache manifest. If the `index.html` was not part of the cached resources you would not be able to start the application off-line.

**Comment by jensborch** [comment]
Right now this does not seem to happen - i.e.  despite a changed mainfest, changes to index.html is not picked up by clients, preventing them from seeing new features. As you are pointing out Gript actually seems to be doing everything correctly, so this might not be a Gript error.  Will research some more... maybe the server is serving the mainfest file with incorrect cache headers. Do you know anything we should be aware of?

**Comment by langecode** [comment]
Actually it will not refresh in the first go.

What happens, when a new manifest is detected, is that the browser starts
the old application while refreshing the cache in the background. Then
afterwards a refresh of the application should trigger your new version to
be loaded.

There is a java script api to see if there is new "versions" of the
application and interact with the AppCache setup. I am pretty sure this is
how, e.g., Google Inbox shows the "New version available" notice. There is
a little bit of showcasing of this in our developer portal (not very
relevant to those reading this on GitHub though).

Den fre. 9. sep. 2016 08.33 skrev Jens Borch Christiansen <
notifications@github.com>:

**Comment by hindsholm** [comment]
Yes, in order to start up the application really fast, it will load directly from cache without even checking the server. After that, it will check the server to see if there is a new manifest, and if there is, it will download the entire application in the background. And as Thor points out, there is an API that the application can use to interact with this mechanism, but basically, you need to somehow reload the application after it has been downloaded.

However, the app-cache mechanism is [in the process of being removed from the HTML spec](https://html.spec.whatwg.org/multipage/browsers.html#offline) so we need to think about how to handle offline applications in the future, probably using [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers) (which are also integrated in Angular2).
